name: mobot_controller
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.19.4 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  toast: ^0.3.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
platforms:
  android:
